import { Tour } from 'nextstepjs';

export const steps: Tour[] = [
  {
    tour: 'mainTour',
    steps: [
      {
        icon: '👋',
        title: '¡Bienvenido a CourelEnergy!',
        content: 'Este tutorial te guiará por las funciones básicas para que puedas empezar a ahorrar en tu factura de la luz.',
        selector: '#dashboard-nav',
        side: 'bottom',
        showControls: true,
        showSkip: true,
      },
      {
        icon: '⚙️',
        title: 'Configuración',
        content: 'Aquí puedes configurar tus datos de usuario, potencias contratadas y añadir tus propias tarifas para comparar.',
        selector: '#step-config',
        side: 'bottom',
        showControls: true,
        showSkip: true,
      },
      {
        icon: '➕',
        title: 'Añadir Tarifas',
        content: 'Usa este botón para añadir una nueva tarifa. Solo necesitas los precios de potencia y energía de tu contrato.',
        selector: '#add-rate-btn',
        side: 'left',
        showControls: true,
        showSkip: true,
      },
      {
        icon: '📊',
        title: 'Tus Consumos',
        content: 'En esta pestaña podrás introducir tus consumos mensuales. Cuantos más meses añadas, más precisa será la comparativa.',
        selector: '#step-consumos',
        side: 'bottom',
        showControls: true,
        showSkip: true,
      },
      {
        icon: '📝',
        title: 'Añadir Consumo',
        content: 'Pulsa aquí para añadir los datos de una factura. Puedes encontrar estos datos en el área de cliente de tu distribuidora o en tu factura en papel.',
        selector: '#add-consumption-btn',
        side: 'left',
        showControls: true,
        showSkip: true,
      },
      {
        icon: '🏆',
        title: 'Resultados y Ahorro',
        content: 'Una vez tengas tarifas y consumos, aquí verás qué tarifa te sale más barata y cuánto podrías ahorrar al año.',
        selector: '#step-resultados',
        side: 'bottom',
        showControls: true,
        showSkip: true,
      },
      {
        icon: '📈',
        title: 'Ranking Comparativo',
        content: 'Aquí verás todas tus tarifas ordenadas por precio anual. ¡La más barata siempre aparecerá la primera!',
        selector: '#ranking-section',
        side: 'top',
        showControls: true,
        showSkip: true,
      },
      {
        icon: '🎉',
        title: '¡Todo listo!',
        content: 'Ya puedes empezar a usar CourelEnergy. Si tienes cualquier duda, puedes consultar la sección de Ayuda en cualquier momento.',
        showControls: true,
        showSkip: false,
      },
    ],
  },
];
